[package]
name = "ckb-gen-type-migrate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1.10.6"
clap = { version = "4", features = ["cargo"] }
